spring:
  profiles:
    active: dev


  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: db1
    password: db1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      connection-test-query: SELECT 1 FROM SYS.DUAL
      minimum-idle: 5
      connection-timeout: 100000


  devtools:
    livereload:
      enabled: true


server:
  port: 8888